### ISSUE TITLE
Multi GPU Support?

### ISSUE THREAD

**Issue by thomasmooon** [sramirez/fast-mRMR#4]
I'm aiming to try this out to and have a general question:
Is it possible to adress a particular GPU, since my DL machine provides 8 GPUs?
This might result in a huge performance boost.
If multi-GPU is not supported, which one will be chosen?

**Comment by sramirez** [comment]
Hi,
Multi-GPU support was not included in the first version, but you can decide among the entire list of GPUs which one will be hosting the main process. However, this issue is out of the scope of this forum as it is common to other CUDA programs. Please refer to the CUDA doc for more details.

**Comment by thomasmooon** [comment]
Thank you!
