### ISSUE TITLE
Output: Only feature ranking?

### ISSUE THREAD

**Issue by thomasmooon** [sramirez/fast-mRMR#5]
Your info files for [CPU](https://github.com/sramirez/fast-mRMR/wiki/CPU-version) and [GPU](https://github.com/sramirez/fast-mRMR/wiki/GPU-version) say, that

> fast-mRMR's output consists of a ranking of features separated by commas (in descending order):
> ./fast-mrmr
> `765,1582,1672,513,1671,1325,1381,1972,1423,1412`

Anything else that will be provided? E. g.
- mutual information matrix
- mutual information for each feature

If not any, this (great) implementation would be useless for my purposes.

**Comment by sramirez** [comment]
I'm sorry that the software is useless for your purposes, but the doc is right. You can always extend it to show MI rates. The community and I will be extremely grateful for it. Just raise a pull request if you feel eager to do the PR.

**Comment by thomasmooon** [comment]
That's a pitty. Unfortunately I don't have the programming skills in C++ / CUDA to do this.

**Comment by thomasmooon** [comment]
Thank you for your lightning quick response + clarification!
